version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    executor: node/default
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages:
          cache-only-lockfile: true 
          check-cache: never 
          include-branch-in-cache-key: true 
          pkg-manager: npm 
          with-cache: true 
      - run:
          command: npm run test
          name: Run tests

  publish:
    executor: node/default
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages
      - run:
          name: Run semantic-release
          command: npm run semantic-release
          environment:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

workflows:
  build_test_deploy:
    jobs:
      - test:
          matrix:
              parameters:
                node-version: ["16.20.2", "18.18.2", "20.9.0"]
      - publish:
          node-version: "18.18.2"
          requires:
            - test
          filters:
            branches:
              only: main