version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  publish:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  build_test_deploy:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: main